version: '3.9'

services:
  web:
    build: .
    command: python /codes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codes
    ports:
      - 8000:8000
#    depends_on:
#      - db
#    environment:
#      - "DJANGO_SECRET_KEY=django-insecure-6s(8*(_2bz$$*wje80jnp%fmg97b_mlpxpz^b6ar7j1$$il!3w$$7"
#      - "DJANGO_DEBUG=True"

  db:
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
