# Generated by Django 4.2.15 on 2024-08-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_alter_comment_body'),
        ('lawandorder', '0002_order_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lawandorder.order')),
                ('productt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.prod')),
            ],
        ),
    ]
