# Generated by Django 4.2.15 on 2024-08-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='prodd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commennnts', to='productions.prod'),
        ),
    ]
