# Generated by Django 4.2.15 on 2024-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_alter_comment_prodd'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='image',
            field=models.ImageField(blank=True, upload_to='productions/img', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'horrible'), ('2', 'bad'), ('3', 'ok'), ('4', 'good'), ('5', 'perfecto')], max_length=10, verbose_name='rating'),
        ),
    ]
