# Generated by Django 4.2.15 on 2024-08-20 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_prod_image_alter_comment_body_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.ImageField(blank=True, upload_to='productions/img/w', verbose_name='image'),
        ),
    ]
