# Generated by Django 4.2.15 on 2024-08-21 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_alter_prod_date_alter_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
