# Generated by Django 4.2.15 on 2024-08-21 17:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_alter_prod_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='short_desc',
            field=models.TextField(blank=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='details'),
        ),
    ]
